### ISSUE TITLE
UI differences

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/vl-sms-app#1]
UI differences:

I.
 As per requirement:
- Reference ID - Grayed out
- Tour Name : Black
![image](https://user-images.githubusercontent.com/35555935/35383197-987d94c8-01e7-11e8-80c3-a4f8e14c4d61.png)
Currently displayed both in black
![image](https://user-images.githubusercontent.com/35555935/35383248-bc70d34a-01e7-11e8-81c0-8c608a3e4b8e.png)

II.
Expected: Bold + Status Color
![image](https://user-images.githubusercontent.com/35555935/35383792-4da1d552-01e9-11e8-8ed6-e8fbc305867f.png)

Actual:

![image](https://user-images.githubusercontent.com/35555935/35383784-401c5510-01e9-11e8-8257-3292d3715fd9.png)

**Comment by ajajrajguru** [comment]
Its already fixed please hard refresh

**Comment by SavantMaithili** [comment]
Please also see the status colors, issue persists
![image](https://user-images.githubusercontent.com/35555935/35386676-ec239900-01f2-11e8-9a00-d6f70464f8bf.png)

**Comment by ajajrajguru** [comment]
Getting wrong labels @cyrus2021 is looking into it

**Comment by SavantMaithili** [comment]
works

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35621817-b80fd5c6-06ab-11e8-9404-7a575112f127.png)

**Comment by SavantMaithili** [comment]
Issue persists

**Comment by cyrus2021** [comment]
Was updated from static html to dynamic content. Issue is fixed now.

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35903029-703710ea-0c03-11e8-9758-51e3e7d1b910.png)
