### ISSUE TITLE
Clearing filters does not refresh records on screen

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/vl-sms-app#15]
![image](https://user-images.githubusercontent.com/35555935/35561659-0d75e99a-05d7-11e8-9cad-dbcff743b4e6.png)
Clear filters, hit the 'Show Participants' button, data remains same
![image](https://user-images.githubusercontent.com/35555935/35561694-2af147b2-05d7-11e8-8c05-2aa4bfc2b3e6.png)

**Comment by SavantMaithili** [comment]
Screenshots provided to us is similar though,
![image](https://user-images.githubusercontent.com/35555935/35561956-e7d4f7a2-05d7-11e8-8a17-bbd65b232c0a.png)

**Comment by cyrus2021** [comment]
UI functionality has been redone

**Comment by SavantMaithili** [comment]
Records are still populated, just the trip name is removed.
![image](https://user-images.githubusercontent.com/35555935/35605644-0bd3ecce-0670-11e8-9fae-44b78945769f.png)

**Comment by SavantMaithili** [comment]
Works!, clearing tour freezes departure dates and show participants button
![image](https://user-images.githubusercontent.com/35555935/35666881-b94d1d4e-0751-11e8-9eec-51fc4c94d804.png)
