### ISSUE TITLE
Filter default pointers

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/vl-sms-app#16]
Select a filter, in this scenario the selected tour code is as in below screenshot
![image](https://user-images.githubusercontent.com/35555935/35562144-7bde7478-05d8-11e8-8d16-d8932117894b.png)
Change the filter, click on 'Select a Tour' to choose another set, the search should be scrolled by default to the value last selected. Here, search starts from the 1st record again 
![image](https://user-images.githubusercontent.com/35555935/35562230-c1ca79f0-05d8-11e8-99a4-568284c0f87e.png)

**Comment by cyrus2021** [comment]
on click of the trip select drop down default values are populated

**Comment by SavantMaithili** [comment]
Closing based on discussion, no changes.
