### ISSUE TITLE
Too long Tour names 

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/vl-sms-app#2]
Actual:
![image](https://user-images.githubusercontent.com/35555935/35383988-ef854ba6-01e9-11e8-8399-518eee304b44.png)

Expected: Truncate (replace with ..) too long characters, as in below screenshot. Tool tip can be used!
![image](https://user-images.githubusercontent.com/35555935/35384006-fdd8ca98-01e9-11e8-9613-428307560465.png)

**Comment by SavantMaithili** [comment]
Issue perists, tried after refresh
![image](https://user-images.githubusercontent.com/35555935/35390031-0e54d8b0-0200-11e8-81ec-75a81a91608a.png)

**Comment by ajajrajguru** [comment]
Fixed
