### ISSUE TITLE
Tour Filter - Long tour name characters jump outside the filter box on the screen

### ISSUE THREAD

**Issue by SavantMaithili** [ajency/vl-sms-app#5]
![image](https://user-images.githubusercontent.com/35555935/35384922-cd7401a8-01ec-11e8-9bbe-bbcd1f1d19ab.png)

**Comment by ajajrajguru** [comment]
Its fixed please hard refresh

**Comment by SavantMaithili** [comment]
![image](https://user-images.githubusercontent.com/35555935/35390115-4e39a38e-0200-11e8-915f-3db6a545f4f9.png)
